# Generated by Django 3.0.6 on 2020-05-23 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20200523_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrights',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Client', to_field='pass_id'),
        ),
    ]
